// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCehG7xapkYvwu3mX0j57REEqylbuCZtPs',
    appId: '1:178660943277:web:07e7e1ddcd9f9a3b7bad24',
    messagingSenderId: '178660943277',
    projectId: 'luma-bf0e5',
    authDomain: 'luma-bf0e5.firebaseapp.com',
    storageBucket: 'luma-bf0e5.firebasestorage.app',
    measurementId: 'G-F4C7PQGW6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj0n1Xtib5v5zPfo_aCqEYuhCoqXBf_QI',
    appId: '1:178660943277:android:4d7d4c075f333a5f7bad24',
    messagingSenderId: '178660943277',
    projectId: 'luma-bf0e5',
    storageBucket: 'luma-bf0e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV40qR32As-2n-5KWAYa4Lwjpczy2dVX4',
    appId: '1:178660943277:ios:8bb8a14019d1dea17bad24',
    messagingSenderId: '178660943277',
    projectId: 'luma-bf0e5',
    storageBucket: 'luma-bf0e5.firebasestorage.app',
    iosBundleId: 'com.example.luma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV40qR32As-2n-5KWAYa4Lwjpczy2dVX4',
    appId: '1:178660943277:ios:8bb8a14019d1dea17bad24',
    messagingSenderId: '178660943277',
    projectId: 'luma-bf0e5',
    storageBucket: 'luma-bf0e5.firebasestorage.app',
    iosBundleId: 'com.example.luma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCehG7xapkYvwu3mX0j57REEqylbuCZtPs',
    appId: '1:178660943277:web:75b68ec4a9b8c10f7bad24',
    messagingSenderId: '178660943277',
    projectId: 'luma-bf0e5',
    authDomain: 'luma-bf0e5.firebaseapp.com',
    storageBucket: 'luma-bf0e5.firebasestorage.app',
    measurementId: 'G-V6F59D9V8Y',
  );
}
